#!/usr/bin/env bash

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1
uname -s | grep -q "_NT-" && export WINDOWS=1

if [ $MACOS ]; then
  VSCODE="$HOME/Library/Application Support/Code/User"
elif [ $LINUX ]; then
  VSCODE="$HOME/.config/Code/User"
elif [ $WINDOWS ]; then
  VSCODE="$APPDATA/Code/User"
fi

if [ -d "$VSCODE" ]; then
    rm -rv "$VSCODE/settings.json"
    ln -sv "$DOTFILESDIR/vscode-settings/settings.json" "$VSCODE/settings.json"
fi

for DOTFILE in $(ls -A); do

    if [[ $DOTFILE == .* ]] && [[ $DOTFILE != .git ]]; then
        HOMEFILE="$HOME/$DOTFILE"
        [ -d $DOTFILE ] && DOTFILE="$DOTFILE/"
        DIRFILE="$DOTFILESDIR/$DOTFILE"

        if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]; then
            ln -sfv "$DIRFILE" "$HOMEFILE"
        else
            rm -rv "$HOMEFILE"
            ln -sv "$DIRFILE" "$HOMEFILE"
        fi
    fi
done

if [ $MACOS ]; then

    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.dotfiles/iterm2"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

fi